[package]
name = "factory-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
petgraph = "0.6.4"
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.114"
thiserror = "1.0.57"
itertools = "0.12.1"
rust_decimal = "1.34"
rust_decimal_macros = "1.34"

[lints]
workspace = true
